Always get latest setuptools in Travis
Normally Travis provides setuptools with its Python environment. In
this case it seems we were getting an old, and possibly broken, version
of setuptools. In the Travis install phase we force an upgrade of
setuptools; this solves the build issues:

making output directory...
Exception occurred:
File "<environment marker>", line 1, in <module>
  NameError: name 'platform_system' is not defined

Also passed the -T flag to Travis to get more verbose exception
tracebacks.